spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_pr
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database: postgresql
server:
  port: 8098

